#define SECRET_WIFI_SSID "YOUR SSID"
#define SECRET_WIFI_PASSWORD "YOUR PASSWORD"

#define SECRET_MQTT_SERVER ""
#define SECRET_MQTT_USER ""
#define SECRET_MQTT_PASSWORD ""
#define SECRET_MQTT_PORT 1883
#define SECRET_MQTT_BASETOPIC "dewpoint-vent"
#define SECRET_MQTT_CLIENT_ID "dewpoint-vent"
